spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab305?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:dao/*.xml
server:
  port: 443
  ssl:
    key-store: 1540260516394.pfx
    key-store-password: 1540260516394