
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab305?useAffectedRows=true
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:dao/*.xml